#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : asunder
Version  : 2.9.3
Release  : 2
URL      : http://littlesvr.ca/asunder/releases/asunder-2.9.3.tar.bz2
Source0  : http://littlesvr.ca/asunder/releases/asunder-2.9.3.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: asunder-bin = %{version}-%{release}
Requires: asunder-data = %{version}-%{release}
Requires: asunder-license = %{version}-%{release}
Requires: asunder-locales = %{version}-%{release}
Requires: cdparanoia
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(libcddb)

%description
Asunder
=======
http://littlesvr.ca/asunder
Asunder is a graphical Audio CD ripper and encoder. You can use it to save tracks from an Audio CD as WAV, MP3, OGG, FLAC, and/or Wavpack.

%package bin
Summary: bin components for the asunder package.
Group: Binaries
Requires: asunder-data = %{version}-%{release}
Requires: asunder-license = %{version}-%{release}

%description bin
bin components for the asunder package.


%package data
Summary: data components for the asunder package.
Group: Data

%description data
data components for the asunder package.


%package license
Summary: license components for the asunder package.
Group: Default

%description license
license components for the asunder package.


%package locales
Summary: locales components for the asunder package.
Group: Default

%description locales
locales components for the asunder package.


%prep
%setup -q -n asunder-2.9.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1563984069
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1563984069
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/asunder
cp COPYING %{buildroot}/usr/share/package-licenses/asunder/COPYING
%make_install
%find_lang asunder

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/asunder

%files data
%defattr(-,root,root,-)
/usr/share/applications/asunder.desktop
/usr/share/pixmaps/asunder.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/asunder/COPYING

%files locales -f asunder.lang
%defattr(-,root,root,-)

